licenselink = 'https://github.com/thewatermethod/mattbev.microblogLICENSE'
description = 'Microblog theme ported from Nuxt'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/thewatermethod/mattbev.microblog'


# Taxonomy terms
tags = ['blog']
features = []


# If the theme has a single author
[author]
name = 'Matt Bevilacqua'
homepage = 'https://www.mattbev.com'
